### ISSUE TITLE
How to run the unminified version?

### ISSUE THREAD

**Issue by Tony20221** [ispras/web-scraper-chrome-extension#109]
How to run the unminified version or how does one develop, make changes and run this extension? I know how to use the release version.

**Comment by Yatskov** [comment]
To run unminifed version for example for development purposes follow these steps:
0. install yarn if it does not exis on your computer
1. `git clone https://github.com/ispras/web-scraper-chrome-extension.git && cd web-scraper-chrome-extension`
2. install dependencies `yarn install`
3. run development server `yarn watch:dev`
4. then load in browser created after this command dist folder as described [here](https://github.com/ispras/web-scraper-chrome-extension/blob/master/docs/Installation.md)
after that you could make changes in code and they would be automatically reloaded in chrome. Sometimes you should reopen tab with plugin and changes applied.
