### ISSUE TITLE
How to debug and use breakpoints in JS code which built by Webpack?

### ISSUE THREAD

**Issue by Tony20221** [ispras/web-scraper-chrome-extension#111]
I am using Firefox and I am not finding an easy way to debug and put breakpoints. Webpack puts the code I want to put a breakpoint on in a long line of an eval statement.  I am using yarn watch:dev.

How does one debug and place breakpoints in such code which is hard to read? I am familiar with debugging extensions before the JS code gets built.

**Comment by Hat331** [comment]
1. Run "watch:dev"
2. Open "Add-ons and themes" menu 
3. Click "Tools for all add-ons"
![image](https://user-images.githubusercontent.com/90384982/171837095-917c2c97-6d20-4eff-beec-0c696b2ee7e6.png)
4. Choose "Debug add-ons"
5. Find web-scrapper extension and click on "Inspect" button  ![image](https://user-images.githubusercontent.com/90384982/171837399-d1bda311-c958-4cf1-8a38-e9ebe084269e.png)
6. Choose debug panel   ![image](https://user-images.githubusercontent.com/90384982/171837552-cae11bb0-60c4-49f3-8dab-2b7dcffecefe.png)
7. Here you can find active extension scripts ![image](https://user-images.githubusercontent.com/90384982/171837751-fe2ed99d-727f-4ecc-90f7-0bbe8975f59c.png)
8. On some page open dev-tools pannel and choose Web Scrapper   ![image](https://user-images.githubusercontent.com/90384982/171837910-334f170f-6746-4a66-9f71-50099d4b65b5.png)
9. You may notice how the panel appeared new scripts like "Controller"
10. Profit  ![image](https://user-images.githubusercontent.com/90384982/171841236-ce78a75d-a677-4a45-bab6-8ae0412f6dd7.png)

**Comment by Tony20221** [comment]
Thanks a lot! I didn't think to look under 'Webpack' in there.
