### ISSUE TITLE
Pagination on non-ajax sites

### ISSUE THREAD

**Issue by koseduhemak** [ispras/web-scraper-chrome-extension#113]
Hi there!

I am struggling to create a pagination for a "next"-link (which changes the URL NOT using JavaScript to dynamically load new content).
E.g. have a look at https://www.ader-paris.fr/en/catalog/121109?offset=0. 

On the mentioned page I want to cycle through all pages (1-7) using the "Next" link and extract the data shown below.

Is something like this possible with this extension? I found no way how to do it...

Would be great if you can give me a hint how this can be achieved! 

Thank you for your help!

Best wishes,
koseduhemak

**Comment by Yatskov** [comment]
Yes is is possible. You create selector next_page which is link to the next_page.  Then all extraction selectors should have this next_page also as the parent selector. And this next_page selector should have itself as the parent selector. More you can read in [docs](https://github.com/ispras/web-scraper-chrome-extension/blob/master/docs/Selectors/Link%20selector.md#Handle%20pagination).

**Comment by koseduhemak** [comment]
Thank you very much for the quick response - works as expected!
Wasn't aware of the docs...
