### ISSUE TITLE
multiple startUrls apparently does not working / stop the startUrls pagination when condition

### ISSUE THREAD

**Issue by antonio24073** [ispras/web-scraper-chrome-extension#78]
Hi, 

Good job with the plugin.

Chrome: Version 87.0.4280.141 (Official Build) (64-bit)
Ubuntu 20.04.1 LTS 64-bit

But I'm trying to use this:

```
Supported URL patterns:
1. Numeric with optional step and zero padding – [START_END:STEP] – [001_010:10]
```

my sitemap:

`{"_id":"google","startUrls":["http://google.com.br?id=[001_010:10]"],"selectors":[{"id":"body","selector":"body","type":"SelectorHTML","parentSelectors":["_root"]}]}`

and the pagination does not work.

![image](https://user-images.githubusercontent.com/40250610/105058448-fa6afb80-5a54-11eb-83bb-9e2f5139bdd0.png)
![image](https://user-images.githubusercontent.com/40250610/105058596-26867c80-5a55-11eb-9a4a-84be3cc672ff.png)
![image](https://user-images.githubusercontent.com/40250610/105058849-69e0eb00-5a55-11eb-8cc5-ed8cee9a3412.png)
[log.log](https://github.com/ispras/web-scraper-chrome-extension/files/5837063/log.log)

I tried with 3.6 and it does not work again.

I would like the loop to stop the pagination when conditions like repeated elements or html contain.

Thank you.

**Comment by Yatskov** [comment]
Maybe there is a misunderstanding of documentation,  but you should use url pattern as ` [START-END:STEP] – [001-010:10]`.
 https://github.com/ispras/web-scraper-chrome-extension/blob/master/docs/Scraping%20a%20site.md

**Comment by Yatskov** [comment]
Seems there is a mistake in plugin hints. Will fix it.

**Comment by Yatskov** [comment]
I think in your case you should use this sitemap as example:
 `
{"_id":"google","startUrls":["http://google.com.br?id=[001-010:1]"],"selectors":[{"id":"body","selector":"body","type":"SelectorHTML","parentSelectors":["_root"]}]}
` then it will make requests to: 
https://www.google.com.br/?id=010
...
https://www.google.com.br/?id=001

**Comment by antonio24073** [comment]
It works!!! :)
Until I try to see the monster regex in the Sitemap.js getStartUrls()... Now all everything became clear. kkkk
Add my feature idea to the queue. (I would like the loop to stop the pagination when conditions like repeated elements or html contain).
Thank you very much!!!

**Comment by antonio24073** [comment]
Hi again. Same problem again. I had forgotten. 

In the Edit metadata there is an help:

`1. Numeric with optional step and zero padding – [START_END:STEP] – [001_010:10]`

but the correct is:

`1. Numeric with optional step and zero padding – [START_END:STEP] – [001-010:10]`

with - not _

Please replace it.

Thank you
