### ISSUE TITLE
Does web-scraper-chrome-extension-v0.3.716.zip release work on Chrome Version 97.0.4692.71?

### ISSUE THREAD

**Issue by ugur1yildiz** [ispras/web-scraper-chrome-extension#99]
Firstly it is an awesome extension, thanks,

I try it and it works in someway, 

What is the purposes of Select, Element preview, Data preview of Selector in Selectors and selectors properties pages?
Nothing happens when clicked. 

Is the purpose of Select button to select the element on the web page by mouse click or what?

web-scraper-chrome-extension-v0.3.716.zip
Chrome Version 97.0.4692.71

**Comment by Yatskov** [comment]
Hello. Probably you could find some information about extension in docs files https://github.com/ispras/web-scraper-chrome-extension/tree/master/docs . This extension is open source fork of https://webscraper.io/ plugin, which one day became closed source and made impossible to develop oor own features. So to understand basics of that plugin you can watch tutorial videos about that plugin https://webscraper.io/tutorials and try it on demo sites https://webscraper.io/test-sites. 

Select button makes possible to automatically generate css from point and click interface. So element preview makes preview of elements on page which are selected by this css selector. Data preview can make possible to watch data which would be extracted by this "Selector".
